HairSalon/Models/Client.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Client> Clients { get; set; }
    public DbSet<Stylist> Stylists { get; set; }
    
    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Details  { get; set; }
    public virtual ICollection<Client> Clients { get; set; }

    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index(string sortOrder, string searchString)
    {
      dynamic model = new ExpandoObject();
      ViewBag.ClientSort = sortOrder == "client" ? "client_desc" : "client";
      ViewBag.StylistSort = sortOrder == "stylist" ? "stylist_desc" : "stylist";

      if (!string.IsNullOrEmpty(searchString))
      {
        model.Clients = _db.Clients.Where(client => client.Name.Contains(searchString)).ToList();
      }
      else
      {
        switch(sortOrder)
        {
          case "client":
            model.Clients = _db.Clients.Include(client => client.Stylist)
              .OrderBy(client => client.Name)
              .ToList();
            break;
          case "client_desc":
            model.Clients = _db.Clients.Include(client => client.Stylist)
              .OrderByDescending(client => client.Name)
              .ToList();
            break;
          case "stylist":
            model.Clients = _db.Clients.Include(client => client.Stylist)
              .OrderBy(client => client.Stylist.Name)
              .ToList();
            break;
          case "stylist_desc":
            model.Clients = _db.Clients.Include(client => client.Stylist)
              .OrderByDescending(client => client.Stylist.Name)
              .ToList();
            break;
          default:
            model.Clients = _db.Clients.Include(client => client.Stylist).ToList();
            break;
        }
      }

      model.Stylists = _db.Stylists.ToList();
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(model);
    }

    [HttpPost]
    public ActionResult Index(int StylistId)
    {
      int inputId = StylistId;
      dynamic model = new ExpandoObject();
      model.Clients =  _db.Clients
        .Include(client => client.Stylist)
        .Where(client => client.StylistId == inputId)
        .ToList();
      model.Stylists = _db.Stylists.ToList();
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;
    
    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1 class="jumbotron">Add a new Client</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId);

  @Html.LabelFor(model => model.Name);
  @Html.TextBoxFor(model => model.Name);

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger" >
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>


<p>@Html.ActionLink("Back to Client list", "Index")</p>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1 class="jumbotron">Edit Client</h1>

<h4>Edit this Stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)<br>

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")<br>

  <input type="submit" value="Save" class="btn btn-primary"/>
}

<p>@Html.ActionLink("Back to Clients", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model dynamic;

<h1 class="jumbotron">Clients</h1>

@if (@Model.Stylists.Count == 0)
{
  <h3>No Stylists have been added yet. Would you like to add one now?</h3>
  <h3>@Html.ActionLink("Add a new stylist?", "Create", "Stylists")</h3>
} 
else if (@Model.Clients.Count == 0)
{
  <p>No Clients have been added yet.</p>
  <p>@Html.ActionLink("Add a new Client", "Create")</p>
  <p>@Html.ActionLink("Add a new Stylist", "Create", "Stylists")</p>
}
else
{
@using (Html.BeginForm("Index", "Clients", FormMethod.Getgit))
{
  <p>
  Find by client name: @Html.TextBox("searchString")
  <input type="submit" class="btn btn-primary" value="Search" />
  </p>
}

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">@Html.ActionLink("Client", "Index", new { sortOrder = ViewBag.ClientSort })</th>
      <th scope="col">@Html.ActionLink("Stylist", "Index", new { sortOrder = ViewBag.StylistSort })</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  @foreach (Client client in Model.Clients)
  {
    <tr>
      <th scope="row">@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId})</th>
      <td>@client.Stylist.Name</td>
      <td>@Html.ActionLink("Edit", "Edit", new { id = client.ClientId })</td>
      <td>@Html.ActionLink("Delete", "Delete", new { id = client.ClientId })</td>
    </tr>
  }
  </tbody>
</table>
<p>@Html.ActionLink("Add a new Client", "Create")</p>
<p>@Html.ActionLink("Add a new Stylist", "Create", "Stylists")</p>
}

<h4>Filter clients by stylist:</h4>
@using (Html.BeginForm())
{
  @Html.DropDownList("StylistId")
  <input type="submit" class="btn btn-primary" />
}

<p>@Html.ActionLink("Show all clients", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1 class="jumbotron">Welcome to Eau Claire's Salon</h1>
<h3>@Html.ActionLink("See all Stylists", "Index", "Stylists")</h3>
<h3>@Html.ActionLink("See all Clients", "Index", "Clients")</h3>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurant | To Do List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1 class="jumbotron"> Add a new stylist</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)<br>

  @Html.LabelFor(model => model.Details)
  @Html.TextBoxFor(model => model.Details)<br>
  <input type="submit" value="Add Stylist" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>Are you sure you want to delete this stylist?</h1>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger"/>
}

@Html.ActionLink("Back to Stylists", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylist;

<h1 class="jumbotron">Stylist Details<h1>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Details): @Html.DisplayFor(model => model.Details)</h3>

<p>@Html.ActionLink("Back to Stylist", "Index")</p>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1 class="jumbotron">Edit Stylist</h1>

<h4>Edit this stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)<br>

  @Html.LabelFor(model => model.Details)
  @Html.EditorFor(model => model.Details)<br>

  <input type="submit" value="Save" class="btn btn-primary"/>
}

<p>@Html.ActionLink("Back to Stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h1 class="jumbotron">Stylists</h1>

@if (@Model.Count == 0)
{
  <p>No stylists have been added yet!</p>
}

@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}

<h3>@Html.ActionLink("Add a new stylist", "Create")</h3>
<h3>@Html.ActionLink("Client list", "Index", "Clients")</h3>
<h3>@Html.ActionLink("Home", "Index", "Home")</h3>